### ISSUE TITLE
cant open the .exe

### ISSUE THREAD

**Issue by fafa42069** [amunchet/DodgeOrNot#3]
Traceback (most recent call last):
  File "main.py", line 192, in <module>
  File "main.py", line 27, in show_settings_window
  File "tkinter\__init__.py", line 2080, in wm_iconbitmap
_tkinter.TclError: bitmap "logo.ico" not defined

**Comment by amunchet** [comment]
Can you try downloading this file and putting it in the same place as the exe?

https://github.com/amunchet/DodgeOrNot/blob/master/logo.ico

I'll try to figure out why it didn't bundle it during build.

**Comment by amunchet** [comment]
Okay, I made a new release that I think fixes it.  Thanks for letting me know!

**Comment by fafa42069** [comment]
worked with the icon and now it asks me for the file location of lol. I put this in : C:\Spiele\Rito Gamin\Riot Games\League of Legends and it started but it stays blank now

**Comment by amunchet** [comment]
Yup, it'll wait for you to get into lobby (you can try it with a normal draft), then it will update as the champs are picked.

**Comment by fafa42069** [comment]
i was in a lobby to test it

**Comment by amunchet** [comment]
Oh sorry - you'll need to add "lockfile" at the end of your location.  So for you, it would be  C:\Spiele\Rito Gamin\Riot Games\League of Legends\lockfile

You can also delete the file "lockfile-location" in your directory, then open the LoL Client (basically where you can click queue up - after you log in with username/password) before opening DodgeOrNot (it'll detect the location automatically).

**Comment by fafa42069** [comment]
my client was open  :/ and now it asks for the logo again even though i downloaded the new exe

**Comment by amunchet** [comment]
Hmm, I just tried it again (without downloading the logo.ico) and it worked for me (I'm on my work computer, so it's a fresh installation).  Did Windows rename the exe file (something like DodgeOrNot(1).exe))?  I know I've clicked on the wrong one before (and figured it out after much head scratching).

I'm not sure why it didn't detect your client being open - were you fully logged in?  If it's just in the game selection (like TFT, Valo, or League), I don't think it'll detect - needs to be all the way into the League client itself (just how Riot's internals work I guess).

At any rate, I think adding lockfile at the end of your path will make it work regardless (although at this point, you're probably already in game :) )

**Comment by fafa42069** [comment]
![lol](https://user-images.githubusercontent.com/88407285/209585870-dffa3c0a-e056-4edf-9ef6-6110eb05f120.png)

still not working

**Comment by fafa42069** [comment]
Yea its clean I deleted the old files and have it a empty folder

I was in the Homepage of the LoL client

Nope + Im testing it on smurfs and dodge

**Comment by amunchet** [comment]
Hmm, it's not reading your client quite right.  You wouldn't happen to have multiple installations of League on your computer would you?

The way it works is the LoL client has a little webserver that runs and DodgeOrNot talks to it.  If you're seeing nothing come up, then it doesn't seem like it can read in.

2 things I can think of - you probably already did this, but can you right click on the exe and make sure it's not blocked on Windows?  

The second is to load up the practice tool and lock in a champ.  It should turn the "Our Team" to 0% instead of the -.

Failing that, maybe a restart is in order to try and reset the LoL client's API.

Thanks for working through this with me.

**Comment by fafa42069** [comment]
I will try again tomorrow

**Comment by amunchet** [comment]
I made a new release - there's now a log file that should hopefully be able to tell what's going on (also some small other changes like the logo and how the manual location file is handled).

**Comment by fafa42069** [comment]
works now

**Comment by amunchet** [comment]
Great!  Let me know if you have any other problems.  I'll go ahead and close this issue for now.
